image:
  name: node:22-alpine

stages:
  - run_tests

run_tests_cov:
  stage: run_tests
  image: node:22-bookworm-slim
  before_script:
    - echo "Running tests"
  script:
    - yarn
    - yarn test:cov
  only:
    refs:
      - master
  artifacts:
    when: always
    paths:
      - coverage
    expire_in: 30 days
  tags:
    - docker-runner-gcp
